openapi: 3.0.0
info:
  title: Video to GIF Converter API
  version: 1.0.0
  description: API for converting videos to GIFs and uploading to ImgBB
paths:
  /convert-video-to-gif:
    post:
      tags:
        - Video Conversion
      summary: Convert a video to a GIF and upload to ImgBB
      description: This endpoint accepts a video file, converts it to a GIF, and uploads it to ImgBB without storing it locally. Returns the URL of the uploaded GIF.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
                  description: The video file to convert (mp4, webm, mov, or avi, max 20MB)
              required:
                - video
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  gif_url:
                    type: string
                    example: https://i.ibb.co/abc123/sample.gif
        '400':
          description: Invalid input or upload failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: Invalid video file format
        '500':
          description: Server error during conversion or upload
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: Failed to convert video to GIF